src/pages/index.page.tsx, src/pages/sandbox/colors.page.tsx, src/styles/globals.css, tailwind.config.js
=> feat: add colors

package.json, src/components/forms/Checkbox.tsx, src/components/forms/DatePicker.tsx, src/components/forms/DropzoneInput.tsx, src/components/forms/ErrorMessage.tsx, src/components/forms/FilePreview.tsx, src/components/forms/Input.tsx, src/components/forms/PasswordInput.tsx, src/components/forms/Radio.tsx, src/components/forms/SearchableSelectInput.tsx, src/components/forms/TextArea.tsx, src/components/forms/boilerplate.tsx, src/components/typography/Typography.tsx, src/pages/index.page.tsx, src/pages/sandbox/form.page.tsx, src/styles/globals.css, src/types/dropzone.ts, yarn.lock
Form components, tested for:
- readonly
- disabled
- icons for input
https://user-images.githubusercontent.com/55318172/211809249-a1d7c6e4-0f4d-489e-b4d5-2c8236528ac4.mp4
=> feat: add form components

src/components/buttons/TextButton.tsx, src/components/links/PrimaryLink.tsx, src/pages/index.page.tsx, src/pages/sandbox/text-button.page.tsx
Text Button & Primary Link
Sandbox page are merged into one
**video updated**
https://user-images.githubusercontent.com/55318172/212094309-aacc4af9-bd90-4c33-906b-be8f037afe1d.mp4
=> feat: add TextButton and PrimaryLink

.husky/pre-push, src/components/buttons/Button.tsx, src/components/forms/DatePicker.tsx, src/components/forms/Input.tsx, src/components/forms/PasswordInput.tsx, src/components/forms/SearchableSelectInput.tsx, src/components/links/ButtonLink.tsx, src/pages/index.page.tsx, src/pages/sandbox/button.page.tsx
- Add button component
- Add min-height to Input
[button.webm](https://user-images.githubusercontent.com/68275535/212062548-c465e6d5-dd12-4f1e-a5c7-14baac3f8d75.webm)
=> feat: add Button

src/components/buttons/Button.tsx, src/components/buttons/IconButton.tsx, src/components/links/IconLink.tsx, src/pages/index.page.tsx, src/pages/sandbox/icon-button.page.tsx
- feat: add IconButton and IconLink
- fix: reverse large button responsive style
[Icon-Button-PPDB-Ultimate-Moon-Design-System.webm](https://user-images.githubusercontent.com/68275535/212257816-73789cd8-9361-457f-aab4-8bb2dd013cc2.webm)
=> feat: add IconButton and IconLink

package.json, src/components/DismissableToast.tsx, src/constant/toast.ts, src/hooks/toast/useLoadingToast.tsx, src/hooks/toast/useMutationToast.tsx, src/hooks/toast/useQueryToast.tsx, src/lib/axios-mock.ts, src/lib/axios.ts, src/pages/_app.page.tsx, src/pages/api/mock/login.api.ts, src/pages/api/mock/me.api.ts, src/pages/index.page.tsx, src/pages/sandbox/toast-rq.page.tsx, src/types/api.ts, yarn.lock
- feat: add toast and react query
[Toast-PPDB-Ultimate-Moon-Design-System.webm](https://user-images.githubusercontent.com/68275535/212282086-5b6b85bd-6893-4015-8dda-2bd13b9294c7.webm)
=> feat: add toast and react query

.github/workflows/issue-autolink.yml
=> ci: update issue autolink version

.github/workflows/git-sync.yml
repo will be synced to https://github.com/theodorusclarence/aether-design-system
=> ci: add github sync

package.json, src/components/dialog/BaseDialog.tsx, src/components/layout/Layout.tsx, src/hooks/useDialog.tsx, src/pages/index.page.tsx, src/pages/sandbox/dialog.page.tsx, src/store/useDialogStore.tsx, yarn.lock
=> feat: add dialog

.github/workflows/issue-autolink.yml, src/components/forms/Checkbox.tsx, src/components/forms/Radio.tsx, src/components/forms/SearchableSelectInput.tsx, src/pages/sandbox/form.page.tsx
cursor pointer for select, checkbox, and radio
update autolink to body
refactor react-select styles
https://user-images.githubusercontent.com/55318172/212909364-a329471f-f941-4770-b2b3-6572f6c5774d.mp4
- Resolve #35
=> ci: change autolink to body style

package.json, src/components/Tooltip.tsx, src/components/typography/Typography.tsx, src/pages/index.page.tsx, src/pages/sandbox/tooltip.page.tsx, tailwind.config.js, yarn.lock
- tooltip component, using `tailwindcss-animate` and `radix` library from [shadcn](https://ui.shadcn.com/docs/primitives/tooltip)
- add forward ref to typography, so it can be used by component such as tooltip
https://user-images.githubusercontent.com/55318172/215496036-0b083a48-5fe9-437b-bc37-3a830446f193.mp4
- Resolve #40
=> feat: add tooltip

package.json, src/components/popover/Popover.tsx, src/pages/index.page.tsx, src/pages/sandbox/components/ExamplePopover.tsx, src/pages/sandbox/popover.page.tsx, yarn.lock
popover component
https://user-images.githubusercontent.com/55318172/216819851-5a690425-8d95-4023-bf32-d05bb68500c8.mp4
- Resolve #45
=> feat: add Popover

package.json, src/components/Banner.tsx, src/lib/content/banner.tsx, src/pages/index.page.tsx, src/pages/sandbox/banner.page.tsx, yarn.lock
- Add autoplay banner
[Banner-Aether-Design-System.webm](https://user-images.githubusercontent.com/68275535/216077701-611aafae-aea8-43c5-ba1d-dfd0500a3acc.webm)
- Resolve #42
=> feat: add autoplay banner

src/components/forms/SearchableSelectInput.tsx
- fix: select input error style
=> fix: select input error style

src/components/forms/DatePicker.tsx, src/components/forms/Input.tsx, src/components/forms/PasswordInput.tsx, src/components/forms/SearchableSelectInput.tsx, src/components/forms/TextArea.tsx
=> feat: add container class to form inputs

src/components/forms/SearchableSelectInput.tsx, src/components/forms/ServerSelectInput.tsx, src/pages/api/mock/select-options.api.ts, src/pages/index.page.tsx, src/pages/sandbox/form.page.tsx, src/pages/sandbox/searchable-select-form.page.tsx
will fetch from the server, the way of passing the route will be customizable. Maybe after we get the API specs, then we can decide if we want to hardcode which one should be used for the value and label. Or maybe try to find a more dynamic way.
https://user-images.githubusercontent.com/55318172/220076432-193c7963-cff3-4986-8964-3aa9c5964228.mp4
=> feat: add server select with loading indicator

src/components/forms/DatePicker.tsx, src/components/forms/ErrorMessage.tsx, src/components/forms/Input.tsx, src/components/forms/PasswordInput.tsx, src/components/forms/SearchableSelectInput.tsx, src/components/forms/ServerSelectInput.tsx, src/components/forms/TextArea.tsx
=> Improve Forms

src/components/DismissableToast.tsx
Create a toast system from query parameter
https://user-images.githubusercontent.com/55318172/220958585-370a5358-8a1c-45fa-82f8-c7a8ce580bb7.mp4
=> feat: add toast query param system

.vscode/typescriptreact.code-snippets, src/components/table/PaginatedTable.tsx, src/components/table/ServerTable.tsx, src/components/table/TBody.tsx, src/components/table/THead.tsx, src/components/table/Table.tsx, src/pages/sandbox/table.page.tsx
Behavior:
- If no size & maxSize is set, text won't truncate and will take as much space as the content needs creating an overflow if needed
- If size and maxSize is set, it will be truncated to the pixel specified
=> improve table

package.json, src/components/buttons/Button.tsx, src/components/buttons/IconButton.tsx, src/components/forms/Input.tsx, src/components/links/ButtonLink.tsx, src/components/links/IconLink.tsx, src/pages/sandbox/icon-button.page.tsx, src/styles/globals.css, yarn.lock
https://github.com/ppdbultimate/rapor-jatim-2023/pull/2
=> sync commits

package.json, src/components/forms/FilePreview.tsx, src/components/table/PaginatedTable.tsx, src/components/table/ServerTable.tsx, src/components/table/TBody.tsx, src/lib/table.ts, src/lib/toast.ts, src/pages/api/mock/users.api.ts, src/pages/sandbox/table.page.tsx, yarn.lock
- Toast query param
- Lightbox rotation
[Table-Aether-Design-System.webm](https://user-images.githubusercontent.com/68275535/222684859-2f6a887b-d4c3-412e-856c-253cfcf34553.webm)
=> add missing functionalities

src/components/buttons/Button.tsx, src/components/links/ButtonLink.tsx
feat: adjust button padding proportion
cherry picked from:
rapor-jatim-2023 - da784aaa069f808a1d7fde231c73c49a1d57e5bd
=> feat: adjust button padding proportion

src/components/Banner.tsx
=> feat: adjust banner min height and duration

package.json, src/components/alert/TypographyAlert.tsx, src/components/cards/SimpleCard.tsx, src/pages/index.page.tsx, src/pages/sandbox/typography-alert.page.tsx, tailwind.config.js, yarn.lock
Alert with typography
No need to use Typography component, just use normal <p> tag
=> typography alert

src/components/typography/Typography.tsx, src/pages/sandbox/typography.page.tsx, src/styles/globals.css
Add example to use responsive typography
https://user-images.githubusercontent.com/55318172/223917345-1418084e-e80a-44d6-90a1-7017fd4a8aea.mp4
=> feat: add responsive typography config

.vscode/settings.json, src/components/cards/MacCard.tsx, src/pages/sandbox/mac-cards.page.tsx
=> sync 09 03

src/components/alert/TypographyAlert.tsx, src/components/forms/DropzoneInput.tsx, src/components/layout/forms/DescriptionList.tsx, src/components/table/Filter.tsx
=> Sync 12 mar

src/components/Banner.tsx, src/components/forms/Checkbox.tsx, src/components/forms/Radio.tsx
=> Sync 14 03

.github/pull_request_template.md, src/components/Skeleton.tsx, src/components/cards/StatisticsCard.tsx, src/components/layout/dashboard/Card.tsx, src/pages/index.page.tsx, src/pages/sandbox/statistics-card.page.tsx
- feat: add DevelopmentCard
- chore: update pull request template
- feat: add statistics card component
- fix: card width depends on dashboard layout
=> sync 30mar

package.json, src/components/AdaptiveModal.tsx, src/components/Drawer.tsx, src/components/dialog/BaseDialog.tsx, src/components/modal/Modal.tsx, src/components/modal/RadixModal.tsx, src/hooks/useMediaQuery.tsx, src/pages/index.page.tsx, src/pages/sandbox/adaptive-modal.page.tsx, src/pages/sandbox/components/ExampleAdaptiveModal.tsx, src/pages/sandbox/components/ExampleDrawer.tsx, src/pages/sandbox/components/ExampleRadixModal.tsx, src/pages/sandbox/drawer.page.tsx, src/pages/sandbox/modal.page.tsx, yarn.lock
- [feat: add adaptive modal](https://github.com/ppdbultimate/design-system-moon/pull/86/commits/42d6ba07f52438dd00e00fec8cfe1bc15f0e851c)
- [feat: add drawer](https://github.com/ppdbultimate/design-system-moon/pull/86/commits/b9a8713f51037d638e5a664b3fa0c8d6a69000b2)
- [feat: add radix dialog](https://github.com/ppdbultimate/design-system-moon/pull/86/commits/5251b85ab9a8099d40c8375da6674e6335a2bcc7)
- [feat: add disable click outside behavior to modal](https://github.com/ppdbultimate/design-system-moon/pull/86/commits/47dd46b79db5bb5ce16670f1e42a5f291a98e131)
- https://design-system-moon-git-adaptivemodal-ppdbultimate.vercel.app/sandbox/adaptive-modal
Provide links to test the changes made.
- https://design-system-moon-git-adaptivemodal-ppdbultimate.vercel.app/sandbox/modal
- Resolve #88
=> Adaptive modal

package.json, src/components/SonnerToast.tsx, src/hooks/toast/useMutationToastSonner.tsx, src/pages/index.page.tsx, src/pages/sandbox/sonner-toast.page.tsx, yarn.lock
- [feat: add sonner toaster](https://github.com/ppdbultimate/design-system-moon/commit/c9c4a64628224ecfe04826389a02fa2289c4381a)
[sonner-toater.webm](https://github.com/ppdbultimate/design-system-moon/assets/70748569/e0e09b7d-c795-4fde-83ff-bebc4ffe4511)
=> feat: add sonner toaster

.vscode/settings.json, package.json, src/components/Drawer.tsx, src/components/dialog/AlertDialog.tsx, src/components/dialog/BaseDialog.tsx, src/components/modal/Modal.tsx, src/components/modal/RadixModal.tsx, src/pages/sandbox/components/ExampleAdaptiveModal.tsx, yarn.lock
- [feat: migrate dialog to radix](https://github.com/ppdbultimate/design-system-moon/pull/93/commits/209ee5ac237c3c12e50559e4f76fcb6df641be1e)
- [feat: adjust modal and drawer z-index](https://github.com/ppdbultimate/design-system-moon/pull/93/commits/ba4886b17ac0bba032802a7252fdae73bc573ee3)
- https://design-system-moon-git-i92-migratedialogfro-e93978-ppdbultimate.vercel.app/sandbox/dialog
- https://design-system-moon-git-i92-migratedialogfro-e93978-ppdbultimate.vercel.app/sandbox/adaptive-modal
[dialog.webm](https://github.com/ppdbultimate/design-system-moon/assets/70748569/86124f80-004e-4140-83ff-1be240fb46db)
- Resolve #92
=> feat: migrate dialog to radix
